config/routes.rb
Rails.application.routes.draw do
  root to: 'dashboard#index'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :customers

  resources :customers, :customer_personal_infos, :events, :event_categories, :customer_events

  # Api paths
  mount SohoApi::Base => '/'
  mount GrapeSwaggerRails::Engine => '/swagger'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/customer_event.rb
class CustomerEvent < ApplicationRecord
  belongs_to :event
  belongs_to :customer
  validates_presence_of :event, :customer, :booked_date, :payment_mode

  enum payment_mode: [:card, :cash, :upi, :wallet]
  # enum no_of_ticket: [*1..20]
  scope :card_payment,   ->    { where(payment_mode: 0) }
  scope :booked_date_today, -> { where(booked_date: Time.now) }
  # scope card_payment: { where(payment_mode: :card)}
end

app/controllers/customer_events_controller.rb
class CustomerEventsController < WebController
  before_action :set_customer_event, only: [:show, :edit, :update, :destroy]

  # GET /customer_events
  # GET /customer_events.json
  def index
    @customer_events = CustomerEvent.where(customer_id: current_customer.id)
  end

  # GET /customer_events/1
  # GET /customer_events/1.json
  def show
  end

  # GET /customer_events/new
  def new
    @customer_event = CustomerEvent.new(customer_id: current_customer.id)
  end

  # GET /customer_events/1/edit
  def edit
  end

  # POST /customer_events
  # POST /customer_events.json
  def create
    @customer_event = CustomerEvent.new(customer_event_params.merge({customer_id: current_customer.id}))

    respond_to do |format|
      if @customer_event.save
        format.html { redirect_to @customer_event, notice: 'Customer event was successfully created.' }
        format.json { render :show, status: :created, location: @customer_event }
      else
        format.html { render :new }
        format.json { render json: @customer_event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customer_events/1
  # PATCH/PUT /customer_events/1.json
  def update
    respond_to do |format|
      if @customer_event.update(customer_event_params)
        format.html { redirect_to @customer_event, notice: 'Customer event was successfully updated.' }
        format.json { render :show, status: :ok, location: @customer_event }
      else
        format.html { render :edit }
        format.json { render json: @customer_event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customer_events/1
  # DELETE /customer_events/1.json
  def destroy
    @customer_event.destroy
    respond_to do |format|
      format.html { redirect_to customer_events_url, notice: 'Customer event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer_event
      @customer_event = CustomerEvent.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def customer_event_params
      params.require(:customer_event).permit(:event_id, :customer_id, :booked_date, :no_of_ticket, :payment_mode)
    end
end

app/helpers/customer_events_helper.rb
module CustomerEventsHelper
end

app/views/customer_events/_form.html.erb
<%= form_with(model: customer_event, local: true) do |form| %>
  <% if customer_event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(customer_event.errors.count, "error") %> prohibited this customer_event from being saved:</h2>

      <ul>
        <% customer_event.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="col-3 form-group">
      <%= form.label :event_id, class: "form_label_custom" %>
    </div>
    <div class="form-group">
      <%= form.collection_select(:event_id, Event.all, :id, :name, :prompt => 'Select', class: "form-control")%>
    </div>
  </div>

  <div class="row">
    <div class="col-3 form-group">
      <%= form.label :booked_date, class: "form_label_custom" %>
    </div>
    <div class="form-group">
      <%= form.datetime_select :booked_date, class: "form-control" %>
    </div>
  </div>

  <div class="row">
    <div class="col-3 form-group">
      <%= form.label :no_of_ticket, class: "form_label_custom" %>
    </div>
    <div class="form-group">
      <%= form.number_field :no_of_ticket, class: "form-control" %>
    </div>
  </div>

  <div class="row">
    <div class="col-3 form-group">
      <%= form.label :payment_mode, class: "form_label_custom" %>
    </div>
    <div class="form-group">
      <%= form.select :payment_mode, CustomerEvent.payment_modes.keys.map { |w| [w.humanize, w] }, :prompt => 'Select', class: "form-control" %>
    </div>
  </div>

  <div class="actions">
    <%= form.submit class: "btn btn-success" %>
  </div>
<% end %>

app/views/customer_events/edit.html.erb
<div class="container">
	<h1>Editing Customer Event</h1>

	<%= render 'form', customer_event: @customer_event %>

	<%= link_to 'Back', customer_events_path, class: " btn btn-primary" %>

</div>

app/views/customer_events/index.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>

  <h1>Customer Events</h1>

  <table class="table">
    <thead>
      <tr>
        <th>Event</th>
        <th>Customer</th>
        <th>Booked date</th>
        <th>No of ticket</th>
        <th>Payment mode</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @customer_events.each do |customer_event| %>
        <tr>
          <td><%= customer_event.event.name %></td>
          <td><%= customer_event.customer.present.name %></td>
          <td><%= customer_event.booked_date.strftime("%d-%b-%Y") %></td>
          <td><%= customer_event.no_of_ticket %></td>
          <td><%= customer_event.payment_mode %></td>
          <td><%= link_to 'Show', customer_event %></td>
          <td><%= link_to 'Edit', edit_customer_event_path(customer_event) %></td>
          <td><%= link_to 'Destroy', customer_event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Customer Event', new_customer_event_path, class:"btn btn-primary" %>
</div>

app/views/customer_events/new.html.erb
<h1>New Customer Event</h1>

<%= render 'form', customer_event: @customer_event %>

<%= link_to 'Back', customer_events_path %>

app/views/customer_events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Event:</strong>
  <%= @customer_event.event.name %>
</p>

<p>
  <strong>Customer:</strong>
  <%= @customer_event.customer.present.name %>
</p>

<p>
  <strong>Booked date:</strong>
  <%= @customer_event.booked_date.strftime("%d-%b-%Y") %>
</p>

<p>
  <strong>No of ticket:</strong>
  <%= @customer_event.no_of_ticket %>
</p>

<p>
  <strong>Payment mode:</strong>
  <%= @customer_event.payment_mode %>
</p>

<%= link_to 'Edit', edit_customer_event_path(@customer_event), class: "btn btn-primary" %> |
<%= link_to 'Back', customer_events_path, class: "btn btn-info" %>