config/routes.rb
Rails.application.routes.draw do
  root to: 'dashboard#index'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :customers

  resources :customers, :customer_personal_infos, :events, :event_categories, :customer_events

  # Api paths
  mount SohoApi::Base => '/'
  mount GrapeSwaggerRails::Engine => '/swagger'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one :customer_personal_info, dependent: :destroy

  has_many :customer_hobbies, dependent: :destroy
  has_many :hobbies, through: :customer_hobbies

  has_many :family_members, dependent: :destroy

  has_many :customer_events

  accepts_nested_attributes_for :family_members, :allow_destroy => true

  def present
    CustomerPresenter.new self
  end

  def display_name
    email
  end

end

app/controllers/customers_controller.rb
class CustomersController < WebController
  before_action :set_customer, only: [:show, :edit, :update, :destroy]

  # GET /customers
  # GET /customers.json
  def index
    @customers = Customer.all
  end

  # GET /customers/1
  # GET /customers/1.json
  def show
  end 

  # GET /customers/new
  def new
    @customer = Customer.new
  end

  # GET /customers/1/edit
  def edit
  end

  # POST /customers
  # POST /customers.json
  def create
    @customer = Customer.new(customer_params)

    respond_to do |format|
      if @customer.save
        format.html { redirect_to @customer, notice: 'Customer was successfully created.' }
        format.json { render :show, status: :created, location: @customer }
      else
        format.html { render :new }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customers/1
  # PATCH/PUT /customers/1.json
  def update
    respond_to do |format|
      if @customer.update(customer_params)
        format.html { redirect_to @customer, notice: 'Customer was successfully updated.' }
        format.json { render :show, status: :ok, location: @customer }
      else
        format.html { render :edit }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1
  # DELETE /customers/1.json
  def destroy
    @customer.destroy
    respond_to do |format|
      format.html { redirect_to customers_url, notice: 'Customer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @customer = Customer.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def customer_params
      params.require(:customer).permit(:email, :first_name, :middle_name, :last_name, :age, :date_of_birth)
    end
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/_form.html.erb
<%= form_with(model: customer, local: true, html: {class: 'customer_form'}) do |form| %>
  <% if customer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(customer.errors.count, "error") %> prohibited this customer from being saved:</h2>

      <ul>
        <% customer.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="col-3 form-group">
      <%= form.label :email, class: "form_label_custom" %>
    </div>
    <div class="form-group">
      <%= form.text_field :email, class: "form-control", readonly: true %>
    </div>
  </div>

  <div class="row">
    <div class="col-3 form-group">
    <%= form.label :first_name, class: "form_label_custom" %>
  </div>
  <div class="form-group">
    <%= form.text_field :first_name, class: "form-control" %>
    </div>
  </div>

  <div class="row">
    <div class="col-3 form-group">
    <%= form.label :middle_name, class: "form_label_custom" %>
  </div>
  <div class="form-group">
    <%= form.text_field :middle_name, class: "form-control" %>
    </div>
  </div>

  <div class="row">
    <div class="col-3 form-group">
    <%= form.label :last_name, class: "form_label_custom" %>
  </div>
  <div class="form-group">
    <%= form.text_field :last_name, class: "form-control" %>
    </div>
  </div>

  <div class="row">
    <div class="col-3 form-group">
    <%= form.label :age, class: "form_label_custom" %>
  </div>
  <div class="form-group">
    <%= form.text_field :age, class: "form-control" %>
    </div>
  </div>

  <div class="row">
    <div class="col-3 form-group">
    <%= form.label :date_of_birth, class: "form_label_custom" %>
  </div>
  <div class="form-group">
    <%= form.text_field :date_of_birth, class: "form-control" %>
    </div>
  </div>

  <div class="actions">
    <%= form.submit "Update", class: "btn btn-success" %>
  </div>
<% end %>

app/views/customers/edit.html.erb
<div class="container">
  <div class="row">
    <h2>Editing Customer</h2>
  </div>

  <%= render 'form', customer: @customer %>

  <div class="row">
    <div class="col-1 form-group">
        <%= link_to 'Show', @customer, class: "btn btn-primary" %>
    </div>
  </div>

</div>

app/views/customers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Customers</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>First name</th>
      <th>Middle name</th>
      <th>Last name</th>
      <th>Age</th>
      <th>Date of birth</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @customers.each do |customer| %>
      <tr>
        <td><%= customer.email %></td>
        <td><%= customer.first_name %></td>
        <td><%= customer.middle_name %></td>
        <td><%= customer.last_name %></td>
        <td><%= customer.age %></td>
        <td><%= customer.date_of_birth %></td>
        <td><%= link_to 'Show', customer %></td>
        <td><%= link_to 'Edit', edit_customer_path(customer) %></td>
        <td><%= link_to 'Destroy', customer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Customer', new_customer_path %>

app/views/customers/new.html.erb
<h1>New Customer</h1>

<%= render 'form', customer: @customer %>

<%= link_to 'Back', customers_path %>

app/views/customers/show.html.erb
<div class="container-fluid">
  <p id="notice"><%= notice %></p>

  <h2>Customer profile</h2>

  <div class="row">
    <div class="col-2 form-group">
      <strong>Email:</strong>
    </div>
    <div class="form-group">
      <%= @customer.email %>
    </div>
  </div>

  <div class="row">
    <div class="col-2 form-group">
      <strong>First name:</strong>
    </div>
    <div class="form-group">
      <%= @customer.first_name %>
    </div>
  </div>

  <div class="row">
    <div class="col-2 form-group">
      <strong>Middle name:</strong>
    </div>
    <div class="form-group">
      <%= @customer.middle_name %>
    </div>
  </div>

  <div class="row">
    <div class="col-2 form-group">
      <strong>Last name:</strong>
    </div>
    <div class="form-group">
      <%= @customer.last_name %>
    </div>
  </div>

  <div class="row">
    <div class="col-2 form-group">
      <strong>Age:</strong>
    </div>
    <div class="form-group">
      <%= @customer.age %>
    </div>
  </div>

  <div class="row">
    <div class="col-2 form-group">
      <strong>Date of birth:</strong>
    </div>
    <div class="form-group">
      <%= @customer.date_of_birth %>
    </div>
  </div>

  <div class="row">
    <div class="col-1 form-group">
      <%= link_to 'Edit', edit_customer_path(@customer), class: "btn btn-primary" %>
    </div>
  </div>
</div>