config/routes.rb
Rails.application.routes.draw do
  root to: 'dashboard#index'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :customers

  resources :customers, :customer_personal_infos, :events, :event_categories, :customer_events

  # Api paths
  mount SohoApi::Base => '/'
  mount GrapeSwaggerRails::Engine => '/swagger'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/customer_personal_info.rb
class CustomerPersonalInfo < ApplicationRecord
  belongs_to :customer

  enum gender: [ :male, :female, :not_sure, :prefer_not_to_disclose ]
  enum marital_status: [:single, :married, :divorced, :widowed]

end

app/controllers/customer_personal_infos_controller.rb
class CustomerPersonalInfosController < WebController
  before_action :set_customer_personal_info, only: [:show, :edit, :update, :destroy]

  # GET /customer_personal_infos
  # GET /customer_personal_infos.json
  # def index
  #   @customer_personal_infos = CustomerPersonalInfo.all
  # end

  # GET /customer_personal_infos/1
  # GET /customer_personal_infos/1.json
  def show
  end

  # GET /customer_personal_infos/new
  def new
    @customer_personal_info = CustomerPersonalInfo.new(customer_id: current_customer.id)
  end

  # GET /customer_personal_infos/1/edit
  def edit
  end

  # POST /customer_personal_infos
  # POST /customer_personal_infos.json
  def create
    @customer_personal_info = CustomerPersonalInfo.new(customer_personal_info_params.merge({customer_id: current_customer.id}))
    respond_to do |format|
      if @customer_personal_info.save
        format.html { redirect_to @customer_personal_info, notice: 'Customer personal info was successfully created.' }
        format.json { render :show, status: :created, location: @customer_personal_info }
      else
        format.html { render :new }
        format.json { render json: @customer_personal_info.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customer_personal_infos/1
  # PATCH/PUT /customer_personal_infos/1.json
  def update
    respond_to do |format|
      if @customer_personal_info.update(customer_personal_info_params.merge({customer_id: current_customer.id}))
        format.html { redirect_to @customer_personal_info, notice: 'Customer personal info was successfully updated.' }
        format.json { render :show, status: :ok, location: @customer_personal_info }
      else
        format.html { render :edit }
        format.json { render json: @customer_personal_info.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customer_personal_infos/1
  # DELETE /customer_personal_infos/1.json
  # def destroy
  #   @customer_personal_info.destroy
  #   respond_to do |format|
  #     format.html { redirect_to customer_personal_infos_url, notice: 'Customer personal info was successfully destroyed.' }
  #     format.json { head :no_content }
  #   end
  # end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer_personal_info
      @customer_personal_info = CustomerPersonalInfo.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def customer_personal_info_params
      params.require(:customer_personal_info).permit(:gender, :nationality, :address_1, :address_2, :city, :state, :marital_status, :qualification)
    end
end

app/helpers/customer_personal_infos_helper.rb
module CustomerPersonalInfosHelper
  def get_customer_name customer_id
    Customer.exists?(id: customer_id) ? Customer.find(customer_id).present.name : "Something went wrong"
  end
end

app/views/customer_personal_infos/_form.html.erb
<%= form_with(model: customer_personal_info, local: true, html: {class: 'customer_form'}) do |form| %>
  <% if customer_personal_info.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(customer_personal_info.errors.count, "error") %> prohibited this customer_personal_info from being saved:</h2>

      <ul>
        <% customer_personal_info.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="col-3 form-group">
      <%= form.label :gender, class: "form_label_custom" %>
    </div>
    <div class="form-group">
      <%= form.text_field :gender, class: "form-control" %>
    </div>
  </div>

  <div class="row">
    <div class="col-3 form-group">
      <%= form.label :nationality, class: "form_label_custom" %>
    </div>
    <div class="form-group">
      <%= form.text_field :nationality, class: "form-control" %>
    </div>
  </div>

  <div class="row">
    <div class="col-3 form-group">
      <%= form.label :address_1, class: "form_label_custom" %>
    </div>
    <div class="form-group">
      <%= form.text_field :address_1, class: "form-control" %>
    </div>
  </div>

  <div class="row">
    <div class="col-3 form-group">
      <%= form.label :address_2, class: "form_label_custom" %>
    </div>
    <div class="form-group">
      <%= form.text_field :address_2, class: "form-control" %>
    </div>
  </div>

  <div class="row">
    <div class="col-3 form-group">
      <%= form.label :city, class: "form_label_custom" %>
    </div>
    <div class="form-group">
      <%= form.text_field :city, class: "form-control" %>
    </div>
  </div>

  <div class="row">
    <div class="col-3 form-group">
      <%= form.label :state, class: "form_label_custom" %>
    </div>
    <div class="form-group">
      <%= form.text_field :state, class: "form-control" %>
    </div>
  </div>

  <div class="row">
    <div class="col-3 form-group">
      <%= form.label :marital_status, class: "form_label_custom" %>
    </div>
    <div class="form-group">
      <%= form.text_field :marital_status, class: "form-control" %>
    </div>
  </div>

  <div class="row">
    <div class="col-3 form-group">
      <%= form.label :qualification, class: "form_label_custom" %>
    </div>
    <div class="form-group">
      <%= form.text_field :qualification, class: "form-control" %>
    </div>
  </div>

  <div class="actions">
    <%= form.submit class: "btn btn-success" %>
  </div>
<% end %>

app/views/customer_personal_infos/edit.html.erb
<div class="container">
  <div class="row">
    <h2>Editing Customer Personal Info</h2>
  </div>

<%= render 'form', customer_personal_info: @customer_personal_info %>

  <div class="row">
    <div class="col-1 form-group">
      <%= link_to 'Show', @customer_personal_info, class: "btn btn-primary" %>
    </div>
  </div>
</div>

app/views/customer_personal_infos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Customer Personal Infos</h1>

<table>
  <thead>
    <tr>
      <th>Gender</th>
      <th>Nationality</th>
      <th>Address 1</th>
      <th>Address 2</th>
      <th>City</th>
      <th>State</th>
      <th>Marital status</th>
      <th>Qualification</th>
      <th>Customer</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @customer_personal_infos.each do |customer_personal_info| %>
      <tr>
        <td><%= customer_personal_info.gender %></td>
        <td><%= customer_personal_info.nationality %></td>
        <td><%= customer_personal_info.address_1 %></td>
        <td><%= customer_personal_info.address_2 %></td>
        <td><%= customer_personal_info.city %></td>
        <td><%= customer_personal_info.state %></td>
        <td><%= customer_personal_info.marital_status %></td>
        <td><%= customer_personal_info.qualification %></td>
        <td><%= customer_personal_info.customer_id %></td>
        <td><%= link_to 'Show', customer_personal_info %></td>
        <td><%= link_to 'Edit', edit_customer_personal_info_path(customer_personal_info) %></td>
        <td><%= link_to 'Destroy', customer_personal_info, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Customer Personal Info', new_customer_personal_info_path %>

app/views/customer_personal_infos/new.html.erb
<h1>New Customer Personal Info</h1>

<%= render 'form', customer_personal_info: @customer_personal_info %>

<%= link_to 'Back', customer_personal_infos_path %>

app/views/customer_personal_infos/show.html.erb
<div class="container-fluid">
  <p id="notice"><%= notice %></p>

  <h2>Customer personal info</h2>

  <div class="row">
    <div class="col-2 form-group">
      <strong>Gender:</strong>
    </div>
    <div class="form-group">
      <%= @customer_personal_info.gender %>
    </div>
  </div>

  <div class="row">
    <div class="col-2 form-group">
      <strong>Nationality:</strong>
    </div>
    <div class="form-group">
      <%= @customer_personal_info.nationality %>
    </div>
  </div>

  <div class="row">
    <div class="col-2 form-group">
      <strong>Address 1:</strong>
    </div>
    <div class="form-group">
      <%= @customer_personal_info.address_1 %>
    </div>
  </div>

  <div class="row">
    <div class="col-2 form-group">
      <strong>Address 2:</strong>
    </div>
    <div class="form-group">
      <%= @customer_personal_info.address_2 %>
    </div>
  </div>

  <div class="row">
    <div class="col-2 form-group">
      <strong>City:</strong>
    </div>
    <div class="form-group">
      <%= @customer_personal_info.city %>
    </div>
  </div>

  <div class="row">
    <div class="col-2 form-group">
      <strong>State:</strong>
    </div>
    <div class="form-group">
      <%= @customer_personal_info.state %>
    </div>
  </div>

  <div class="row">
    <div class="col-2 form-group">
      <strong>Marital status:</strong>
    </div>
    <div class="form-group">
      <%= @customer_personal_info.marital_status %>
    </div>
  </div>

  <div class="row">
    <div class="col-2 form-group">
      <strong>Qualification:</strong>
    </div>
    <div class="form-group">
      <%= @customer_personal_info.qualification %>
    </div>
  </div>

  <div class="row">
    <div class="col-2 form-group">
      <strong>Customer:</strong>
    </div>
    <div class="form-group">
      <%= get_customer_name(@customer_personal_info.customer_id) %>
    </div>
  </div>

  <div class="row">
    <div class="col-1 form-group">
      <%= link_to 'Edit', edit_customer_personal_info_path(@customer_personal_info), class: "btn btn-primary" %>
    </div>
  </div>
</div>