config/routes.rb
Rails.application.routes.draw do
  root to: 'dashboard#index'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :customers

  resources :customers, :customer_personal_infos, :events, :event_categories, :customer_events

  # Api paths
  mount SohoApi::Base => '/'
  mount GrapeSwaggerRails::Engine => '/swagger'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one :customer_personal_info, dependent: :destroy

  has_many :customer_hobbies, dependent: :destroy
  has_many :hobbies, through: :customer_hobbies

  has_many :family_members, dependent: :destroy

  has_many :customer_events

  accepts_nested_attributes_for :family_members, :allow_destroy => true

  def present
    CustomerPresenter.new self
  end

  def display_name
    email
  end

end

app/models/customer_event.rb
class CustomerEvent < ApplicationRecord
  belongs_to :event
  belongs_to :customer
  validates_presence_of :event, :customer, :booked_date, :payment_mode

  enum payment_mode: [:card, :cash, :upi, :wallet]
  # enum no_of_ticket: [*1..20]
  scope :card_payment,   ->    { where(payment_mode: 0) }
  scope :booked_date_today, -> { where(booked_date: Time.now) }
  # scope card_payment: { where(payment_mode: :card)}
end

app/models/customer_family.rb
class CustomerFamily < ApplicationRecord
end

app/models/customer_hobby.rb
class CustomerHobby < ApplicationRecord
   belongs_to :customer
   belongs_to :hobby

end

app/models/customer_personal_info.rb
class CustomerPersonalInfo < ApplicationRecord
  belongs_to :customer

  enum gender: [ :male, :female, :not_sure, :prefer_not_to_disclose ]
  enum marital_status: [:single, :married, :divorced, :widowed]

end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :event_category
  has_many :customer_events
  validates_presence_of :name, :event_category, :event_date, :event_price
end

app/models/event_category.rb
class EventCategory < ApplicationRecord
  has_many :events, dependent: :destroy
  validates_presence_of :name
end

app/models/family_member.rb
class FamilyMember < ApplicationRecord

  enum relationship: [ :parents, :wife, :child ]
  enum role: [:father, :mother, :son, :daughter]

  validates :name, presence: true, uniqueness: true

  belongs_to :customer

end

app/models/hobby.rb
class Hobby < ApplicationRecord
end

app/controllers/customers_controller.rb
class CustomersController < WebController
  before_action :set_customer, only: [:show, :edit, :update, :destroy]

  # GET /customers
  # GET /customers.json
  def index
    @customers = Customer.all
  end

  # GET /customers/1
  # GET /customers/1.json
  def show
  end 

  # GET /customers/new
  def new
    @customer = Customer.new
  end

  # GET /customers/1/edit
  def edit
  end

  # POST /customers
  # POST /customers.json
  def create
    @customer = Customer.new(customer_params)

    respond_to do |format|
      if @customer.save
        format.html { redirect_to @customer, notice: 'Customer was successfully created.' }
        format.json { render :show, status: :created, location: @customer }
      else
        format.html { render :new }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customers/1
  # PATCH/PUT /customers/1.json
  def update
    respond_to do |format|
      if @customer.update(customer_params)
        format.html { redirect_to @customer, notice: 'Customer was successfully updated.' }
        format.json { render :show, status: :ok, location: @customer }
      else
        format.html { render :edit }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1
  # DELETE /customers/1.json
  def destroy
    @customer.destroy
    respond_to do |format|
      format.html { redirect_to customers_url, notice: 'Customer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @customer = Customer.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def customer_params
      params.require(:customer).permit(:email, :first_name, :middle_name, :last_name, :age, :date_of_birth)
    end
end

app/controllers/events_controller.rb
class EventsController < WebController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def event_params
      params.require(:event).permit(:name, :event_category_id, :event_date, :event_time, :event_price)
    end
end

app/controllers/web_controller.rb
class WebController < ApplicationController
  before_action :authenticate_customer!
end

app/helpers/application_helper.rb
module ApplicationHelper
  def get_customer_info_url
    current_customer.customer_personal_info.nil? ? new_customer_personal_info_path(current_customer) : customer_personal_info_path(current_customer.customer_personal_info.id)
  end
end

app/helpers/customer_events_helper.rb
module CustomerEventsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/event_categories_helper.rb
module EventCategoriesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SohoAdmin</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <!-- Font Awesome JS -->
    <script defer src="https://use.fontawesome.com/releases/v5.0.13/js/solid.js" integrity="sha384-tzzSw1/Vo+0N5UhStP3bvwWPq+uvzCMfrN1fEFe+xBmv1C/AtVX5K0uZtmcHitFZ" crossorigin="anonymous"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.0.13/js/fontawesome.js" integrity="sha384-6OIrr52G08NpOFSZdxxz1xdNSndlD4vdcf/q2myIUVO0VsqaGHJsB0RaBE01VTOY" crossorigin="anonymous"></script>


  </head>

  <body>
      <% if notice %>
        <p class="alert alert-success"><%= notice %></p>
      <% end %>
      <% if alert %>
        <p class="alert alert-danger"><%= alert %></p>
      <% end %>
    <div class="wrapper">
      <!-- Left Sidebar Navigation -->
      <% if current_customer %>
        <%= render partial: "layouts/partials/leftsidebar" %>
      <div id="content">
        <p class="navbar-text float-right">
            Logged in as <strong><%= current_customer.email %></strong>.
    <!--         <%= link_to 'Edit profile', edit_customer_registration_path, :class => 'navbar-link' %> | -->
            <%= link_to "Logout", destroy_customer_session_path, method: :get, :class => 'navbar-link'  %>
        </p>
          <%= yield %>
      </div>
      <% else %>
        <%= yield%>
        <% end %>
    </div>
  </body>
</html>

app/views/layouts/partials/_leftsidebar.html.erb
        <nav id="sidebar">
            <div class="sidebar-header">
                <h3>Soho Events</h3>
            </div>

            <ul class="list-unstyled components">
                <p>Customer Event reporting</p>
                <li class="active">
                    <a href="/">Dashboard</a>
                </li>
                <li>
                  <a href="#pageSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">Customer</a>
                  <ul class="collapse list-unstyled" id="pageSubmenu">
                    <li>
                      <a href="/customers/<%=current_customer.id%>">Profile</a>
                    </li>
                    <li>
                      <%= link_to "Personal info", get_customer_info_url %>
                    </li>
                    <li>
                      <a href="#">Hobby</a>
                    </li>
                    <li>
                      <a href="#">Family Details</a>
                    </li>
                  </ul>
                </li>
                <li>
                  <a href="#pageSubmenu2" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">Events</a>
                  <ul class="collapse list-unstyled" id="pageSubmenu2">
                    <li>
                      <a href="/customer_events">CustomerEvents</a>
                    </li>
                    <li>
                      <%= link_to "All Events", events_path %>
                    </li>
                    <li>
                      <%= link_to "All Event Category", event_categories_path %>
                    </li>
                  </ul>
                </li>
            </ul>
        </nav>